#!/bin/bash

#
# set_application_inputs - Sets application input properties
#

a4cURL="http://localhost:8088"
userName="admin"
password="admin"
applicationName=""
keyaluePairs=""
usage() {
    echo ""
    echo "Usage:"
    echo "set_application_inputs [--a4c-url <Alien4Cloud URL>]"
    echo "                       [--user <Alien4Cloud administrator user name>]"
    echo "                       [--password <Alien4Cloud administrator password>]"
    echo "                       --application <Application Name>"
    echo "                       --inputs \"key1=value1 key2=value2\""
    echo "   - default A4C URL : $a4cURL"
    echo "   - default user    : $userName"
    echo "   - default password: $password"
}

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -a|--a4c-url)
    a4cURL="$2"
    shift # past argument
    shift # past value
    ;;
    -u|--user)
    userName="$2"
    shift # past argument
    shift # past value
    ;;
    -p|--password)
    password="$2"
    shift # past argument
    shift # past value
    ;;
    -n|--application)
    applicationName="$2"
    shift # past argument
    shift # past value
    ;;
    -i|--inputs)
    keyaluePairs="$2"
    shift # past argument
    shift # past value
    ;;
    -h|--help)
    usage
    exit 0
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

if [ -z "$applicationName" ]
then
    echo "Error: missing mandatory parameter application name"
    usage
    exit 1
fi

if [ -z "$keyaluePairs" ]
then
    echo "Error: missing mandatory parameter inputs"
    usage
    exit 1
fi

# Load utilities
declare -r DIR=$(cd "$(dirname "$0")" && pwd)
source $DIR/utils.bash

# First, login and store the cookies
a4c_login "$a4cURL" "$userName" "$password" "cookies.a4c"

# Get the Application environment ID
res=`curl --request POST \
          --url $a4cURL/rest/latest/applications/environments \
          --header 'Content-Type: application/json' \
          --cookie cookies.a4c \
          --silent \
          --data "[\"$applicationName\"]"`
envID=`getJsonval id $res`

if [ -z "$envID" ]
then
    echo "Exiting on error getting the environment ID for Application $applicationName"
    exit 1
fi

# Create the data to post
inputData=""
for keyValuePair in $keyaluePairs; do
    set -- `echo $keyValuePair | tr '=' ' '`
    key=$1
    value=$2
    newInput="\"$key\": \"$value\""
    if [ -z "$inputData" ]
    then
        inputData="$newInput"
    else
        inputData="$inputData, $newInput"
    fi
done
postData="{\"inputProperties\": {$inputData}}"

# Set input parameters
response=`curl --request PUT \
               --url $a4cURL/rest/latest/applications/$applicationName/environments/$envID/deployment-topology \
               --header 'Content-Type: application/json' \
               --cookie cookies.a4c \
               --silent \
               --data "$postData"`

res=$?
if [ $res -ne 0 ]
then
    echo "Exiting on error creating application $applicationName : $response"
    exit 1
fi

echo "Input parameters set on Application $applicationName"