language: java

jdk:
  - oraclejdk8

install:
  - pip install --user --upgrade sphinx==1.7.9 semantic-version requests urllib3[secure]

script:
  - sudo cp fastconnect.org.crt /usr/local/share/ca-certificates/
  - sudo update-ca-certificates
  - mvn clean verify -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true

deploy:
  - provider: script
    script: bash deploy.sh
    on:
      all_branches: true
    skip_cleanup: true

  - provider: script
    script: bash cleanup_bintray.sh
    on:
      all_branches: true
    skip_cleanup: true

  - provider: releases
    overwrite: true
    file_glob: true
    api_key:
      secure: kXuP0Wz/tvm+F5pdCqSC2rRTiWIdVbnqxImeOn/1MfIYekcYkKjEfKO0UnL/FCJJ1MdNmZ6Q5Yn8aTZiUBXZeRiKLs/C2ka7cnwyGjXq2vykc11bPqr44o1J+sNuq85nxtKLIfXK+I4AfcmlBtofDVEBi6FFb+YXPFJRlowDqqbReKv8se0Ik5vcARBhrO/I30GuWP8Pf8AaiSrBYDvln1DazPKekR/mq3vhh5pW/WPfZW/gscXtuBUDU67eAhgh9JFLk/LiOOXNbnuQD2bfkFztZRVLbyt/FfJJHv78MXFslcGIvMR6wsG8WaPQuYh/36L1025dnIdFp7zranqlgk/heObzEOsyd+zb2yQyQJIan252EZbruf9m2/HlaiFR32QdQ6aSTa4JFbmp4e6FHxkU1eOerPiHMJwzelG1BXQaDBlo/5rfJSNGAOQmUAj13Kem2U3DcL8eQ7nfQaCTr0d7iOQTTxkzouSkIr3du5VlisaxR4zn+1MrxELmYBXNIpYCXOyqgpDRxLZ6dmBsNBMMcyFlzxULkfoSMb4DDiMyqlDddexcakvkqwzC6X5SmZCwRMQvZmVdsqupHS/KaiJWjGhl0ahIaCEUtW+jveVPScIGc0Vmje3Lnx8uh+Keuqu8Sr2uraVG/VVInYJsVKuVYNKD+8HLPxyXnZZVpig=
    file:
      - distribution/target/alien4cloud-yorc-plugin-distribution-*.zip
      - alien4cloud-yorc-plugin/target/alien4cloud-yorc-plugin-*.zip
    skip_cleanup: true
    on:
      tags: true

addons:
  apt:
    packages:
    - jq
    - latexmk
    - texlive-binaries
    - texlive-fonts-recommended
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-latex-recommended

env:
  global:
    secure: UYRcG6VFZrs26zy+L3p6AgfAfIjCU9VTHHeaTqDZ7mYSKl7ijn4Av/tYna/gblftq9k5Lh1pPW54q2pkdl0d9KPA6fDbsi1AGpBg3smVZ3znzC+N6Y/MUZvyI6UkmjC00tCwCBouB2E8mQ/7xLBfX/bY4QqZBiOWr86eTULBhW1og0PbATBggPLdrHXouC3NVB8/MrhWBssoGNYnBxeHDmmPklhwx1tHEfEIh+QKsDOmm4AVLVb/ZFLziIr/eQ0k8vqU9/nRKZY1ZQ4gOmnWZ/74AC7e2EwcYWcjVK62rE4ePE86LL3zpqfnFFgu/v5d5l8m8yoMTOYx09pL/6Zbw280ahit/P7oDUtSyx+Vejv3hPDkupmKcxqeTEpkRxmDWNu6dYOeuMGo3P3uVbKA7SaqZTjxNDhxAvaMxwUg4rR44o1Vxwz6VVAZPIcMdoYlN/LDn1oJCx4bWL9p+P0MIPZp4H0NnE5N//MgZLoy2GueBGSVrx7c272H8FaC+er7ZzItCm3qUKAKR4CYoogdDK9avuhw+Wy180FfVE1dUZzNKkEZfDKxz33AXqwnsaCtcmMkv/qccpVtTJ1NnVuvaHRReMT2bLZhQLBk73/380lrbc6XPlJJh1l7YzP0IarChWVxynA4qb5qIXTiuoXifSfV5xcDNT8UkKuh5Vw1bXM=

cache:
  directories:
    - $HOME/.m2/repository

