tosca_definitions_version: alien_dsl_2_0_0

metadata:
  template_name: KubeJobFail
  template_version: 0.1.0-SNAPSHOT
  template_author: admin

description: ""

imports:
  - tosca-normative-types:1.0.0-ALIEN20
  - docker-types:2.1.1
  - org.ystia.yorc.samples.kube.jobs:1.0.0-SNAPSHOT

topology_template:
  node_templates:
    ContainerJobUnit:
      metadata:
        a4c_edit_x: 130
        a4c_edit_y: "-19"
      type: org.alien4cloud.extended.container.types.ContainerJobUnit
    ContainerRuntime:
      type: org.alien4cloud.extended.container.types.ContainerRuntime
      requirements:
        - hostedOnContainerJobUnitHost:
            type_requirement: host
            node: ContainerJobUnit
            capability: tosca.capabilities.Container.Docker
            relationship: tosca.relationships.HostedOn
    ComputeFail:
      type: org.ystia.yorc.samples.kube.containers.nodes.ComputeFail
      properties:
        docker_run_cmd: 
          - "/bin/bash"
          - "-c"
          - "sleep 10; >&2 echo 'Computation Failed!'; exit 1"
        cpu_share: 1.0
        mem_share: "128 MB"
        docker_bash_cmd: 
          - "/bin/bash"
          - "-c"
      requirements:
        - hostedOnContainerRuntimeContainerRuntimeHost:
            type_requirement: host
            node: ContainerRuntime
            capability: org.alien4cloud.extended.container.capabilities.ApplicationHost
            relationship: org.alien4cloud.extended.container.relationships.HostedOnContainerRuntime
      capabilities:
        scalable:
          properties:
            min_instances: 1
            max_instances: 1
            default_instances: 1
