id: alien4cloud-yorc-plugin
name: Yorc Orchestrator Provider
version: ${project.version}
description: >
  Plugin that contains a single paas provider for deployments on Hpc env.
configuration_class: org.ystia.yorc.alien4cloud.plugin.YorcPluginConfiguration
component_descriptors:
  - bean_name: yorc-orchestrator-factory
    name: Yorc Orchestrator Factory
    description: >
      Alien Plugin for Yorc
  - bean_name: yorc-kubernetes-modifier
    name: Yorc Modifier for Kubernetes
    description: >
      Yorc Modifier for Kubernetes
  - bean_name: yorc-openstack-server-group-modifier
    name: Openstack modifier for Server Group affinity and anti-affinity policies
    description: Openstack modifier for Server Group affinity and anti-affinity policies
  - bean_name: yorc-monitoring-modifier
    name: Yorc modifier for handling monitoring policies
    description: Yorc modifier for handling monitoring policies
dependencies:
  - alien4cloud-kubernetes-plugin
